### ISSUE TITLE
Monospace

### ISSUE THREAD

**Issue by jonasborggren** [marcologous/genome#2]
Having this in my IDE would mean world peace. Pretty please.

**Comment by marcologous** [comment]
:) You can have it

**Comment by jonasborggren** [comment]
Yes, but it would require a monospaced font (fixed width/pitch). Is that already available?

**Comment by marcologous** [comment]
Oh! I do have a prototype but the symbols are not complete yet, plus is your IDE dark background? because if it is light you might have issues with reading. The monospace is still under development and the incomplete set will be added here next week.

**Comment by jonasborggren** [comment]
OK. My IDE has a light background so I guess that would be a problem then. How come it's a problem with white backgrounds? Looks fine on the preview on Behance.

Very nice. Looking forward to it.

**Comment by marcologous** [comment]
Hey no worries. I am developing the monospaced anyway. But if you don't have any problems with the weight then I am happy with that :dancers: 

Next week monday will post the monospaced version! Wohooooo!

**Comment by jonasborggren** [comment]
Very nice. Can't wait.
